name: Changesets

on:
  push:
    branches:
      - '[0-9]+-[0-9]+'

jobs:
  changelog:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'shopify'
    name: Changelog PR or Release
    outputs:
      published: ${{ steps.changesets.outputs.published }}
      latest: ${{ steps.flags.outputs.latest }}
    steps:
      - name: Flags
        id: flags
        run: |
          # IMPORTANT: Update this variable whenever we move to a new major version:
          latest_branch=2022-7
          echo "::set-output name=latest::${{ github.ref_name == '2022-7' }}"

      - name: Checkout the code
        uses: actions/checkout@v3
        # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install the packages
        run: yarn install --frozen-lockfile --ignore-engines

      - name: (latest) Create Release Pull Request or Publish
        if: steps.flags.outputs.latest == 'true'
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn changeset publish
          commit: '[ci] release ${{ github.ref_name }}'
          title: '[ci] release ${{ github.ref_name }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: (legacy) Create Release Pull Request or Publish
        if: steps.flags.outputs.latest != 'true'
        id: changesets_legacy
        uses: changesets/action@v1
        with:
          publish: yarn changeset publish --tag legacy
          commit: '[ci] release ${{ github.ref_name }}'
          title: '[ci] release ${{ github.ref_name }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # note that this runs on every PR that's merged.
      - name: (next) Create Release Pull Request or Publish
        id: changesets_next
        run: cd packages/react/scripts && node prepare-next.js
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
