name: Releases

on:
  push:
    branches:
      - '[0-9]+-[0-9]+'

jobs:
  Releases:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'shopify'
    name: Releases and PR for changesets
    outputs:
      published: ${{ steps.changesets.outputs.published }}
      latest: ${{ env.latest }}
    steps:
      - name: Flags
        id: flags
        run: |
          # IMPORTANT: Update this variable whenever we move to a new major version:
          latest_branch=2023-01
          echo "latest=${{ github.ref_name == '2023-01' }}" >> $GITHUB_ENV

      - name: Checkout the code
        uses: actions/checkout@v3
        # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install the packages
        run: npm ci

      - name: (latest) Create Release Pull Request or Publish
        if: env.latest == 'true'
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run changeset publish
          commit: '[ci] release ${{ github.ref_name }}'
          title: '[ci] release ${{ github.ref_name }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: (legacy) Create Release Pull Request or Publish
        if: env.latest != 'true'
        id: changesets_legacy
        uses: changesets/action@v1
        with:
          publish: npm run changeset publish --tag legacy
          commit: '[ci] release ${{ github.ref_name }}'
          title: '[ci] release ${{ github.ref_name }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # note that this runs on every PR that's merged.
      - name: (next) Publish
        id: release_next
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
          cd packages/react/scripts
          node prepare-next.mjs
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
